### ISSUE TITLE
Unable to accept the Pebble Terms of Use

### ISSUE THREAD

**Issue by codeinabox** [pebble/homebrew-pebble-sdk#17]
I am having trouble accepting the terms of use, when I get the prompt I am unable to type `y` or `n`. Below is the output of brew config

> HOMEBREW_VERSION: 0.9.5
> ORIGIN: https://github.com/Homebrew/homebrew.git
> HEAD: 17fc083bd7e56ff10440d8692389d0b63d4ab178
> Last commit: 87 minutes ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_CELLAR: /usr/local/Cellar
> CPU: dual-core 64-bit core2
> OS X: 10.6.8-i386
> Xcode: 3.2.6
> CLT: N/A
> GCC-4.0: build 5494
> GCC-4.2: build 5666
> LLVM-GCC: build 2335
> Clang: 2.0 build 139
> X11: 2.3.6 => /usr/X11
> System Ruby: 1.8.7-p358
> Perl: /usr/bin/perl
> Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/bin/python2.7
> Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.2/bin/ruby
> Java: 1.6.0_65

**Comment by cjwilliams** [comment]
Would you mind running `gem list curses` and pasting the output here for me?

**Comment by codeinabox** [comment]
The only output I get is

> *** LOCAL GEMS ***

**Comment by codeinabox** [comment]
I've tried this in both zsh, bash and using iTerm and Terminal but still can't enter anything. Is there a way to install non-interactively?

**Comment by ktaragorn** [comment]
Me too. Got around it by editing the formula in `/usr/local/Formula/taps/pebble/homebrew-pebble-sdk
/pebble-sdk.rb` to remove the part where it loops waiting for the user.

**Comment by cjwilliams** [comment]
A fix is coming soon that won't require the use of the Curses gem, thanks for your patience =)
