### ISSUE TITLE
Install fails with `ecb_noreturn` error (OSX 10.11)

### ISSUE THREAD

**Issue by matthewberryman** [pebble/homebrew-pebble-sdk#18]
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.1/libexec
libev/ev.c:832:26: note: expanded from macro 'ecb_noreturn'
  #define ecb_noreturn   _Noreturn
                         ^
1 error generated.
error: command 'clang' failed with exit status 1

**Comment by cjwilliams** [comment]
What version of the Pebble SDK were you running prior to upgrading? Could you please paste all of the console output of the brew upgrade command here?

Thanks!

**Comment by matthewberryman** [comment]
Coming from v3.0:
matthew@Clara:~$ brew info pebble-sdk
pebble/pebble-sdk/pebble-sdk: stable 3.1
https://developer.getpebble.com
/usr/local/Cellar/pebble-sdk/3.0 (3421 files, 158M) *
  Built from source

Full console output:
matthew@Clara:~$ brew upgrade pebble-sdk
==> Upgrading 1 outdated package, with result:
pebble/pebble-sdk/pebble-sdk 3.1
==> Upgrading pebble/pebble-sdk/pebble-sdk
==> Downloading https://sdk.getpebble.com/download/3.1?source=homebrew
Already downloaded: /Library/Caches/Homebrew/pebble-sdk-3.1.1
==> Downloading https://pypi.python.org/packages/source/a/autobahn/autobahn-0.5.
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--autobahn-0.5.14.zip
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.1/libexec
==> Downloading https://pypi.python.org/packages/source/b/backports.ssl_match_ho
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--backports.ssl-match-hostname-3.4.0.2.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.1/libexec
==> Downloading https://pypi.python.org/packages/source/f/freetype-py/freetype-p
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--freetype-py-1.0.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.1/libexec
==> Downloading https://pypi.python.org/packages/source/g/gevent/gevent-1.0.2.ta
Already downloaded: /Library/Caches/Homebrew/pebble-sdk--gevent-1.0.2.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.1/libexec
libev/ev.c:832:26: note: expanded from macro 'ecb_noreturn'
  #define ecb_noreturn   _Noreturn
                         ^
1 error generated.
error: command 'clang' failed with exit status 1

**Comment by cjwilliams** [comment]
Thanks for the details. It looks like this is an issue with the gevent dependency: https://github.com/gevent/gevent/commit/23a403dbd7c83811d72fe1a83cc7a4cd698870f0. The fix hasn't been released yet to the public, but we will look into options to fix this.

**Comment by matthewberryman** [comment]
Thanks for checking into it. I'm running 10.10.4, but with Xcode 7 and clang reports "Apple LLVM version 7.0.0 (clang-700.0.53.3)"; running `sudo xcode-select -s /Library/Developer/CommandLineTools` gives me back "Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)", which results in successful compilation of the gevent dependency and successful upgrade of the SDK. Personally, I'm happy to wait until the gevent fix is released.

**Comment by edwinfinch** [comment]
I'm having this issue too :(

**Comment by edwinfinch** [comment]
brew install https://gist.githubusercontent.com/Katharine/02bd07d4e934413504b5/raw/ddf9b060a916620adc380d769ab787699c422b33/pebble-sdk.rb

Run this instead. It swaps out gevent 1.1b1. Thanks Katharine Berry :)

**Comment by geoffballinger** [comment]
I have run into this issue doing a fresh install of the Pebble SDK on Yosemite 10.10.5 with the App Store release version of XCode 7 (so I can play around with my newly arrived Pebble Time Steel ;-).

The xcode-select trick above doesn't work since the clang at that path is also Apple LLVM version 7.0.0 (clang-700.0.72)

I also tried the alternative package from Katherine above but aborted that since it seems to be for an older version of the SDK - v3.2 - which doesn't seem sensible? I guess my best approach would be to take the current v3.4 package and make the same tweak to the gevent version?

Geoff.

**Comment by geoffballinger** [comment]
Yes - that worked. In case anybody else finds it useful prior to the real fix it is up at:

https://gist.githubusercontent.com/geoffballinger/9cc7fa234aa8873fdca1/raw/ba7175eb02b3dd9fd858b9d51599146affe97344/pebble-sdk.rb

Geoff

**Comment by Katharine** [comment]
Yes, that is the recommended solution. I'm waiting on either OS X 10.11 being released or gevent 1.1 being released before updating our version, though.

**Comment by geoffballinger** [comment]
Yes - dependency hell - I definitely feel your pain! This sort of thing is always a bit of a thankless task.

The only thing I would suggest is that I think the OS X side of things is perhaps a red herring. From my digging around this morning the root cause are the clang changes that come along with Xcode 7 - which went live on the app store in the last couple of days.

Anybody setting up a fresh system today with the current release versions of OS X and Xcode from the store will run into this - not an early adopter thing,

G

**Comment by gracelctech** [comment]
After following @edwinfinch's suggestion, I also had to change the line "gevent==1.0.2" to "gevent==1.1b5" in the requirements.txt file in /usr/local/Cellar/pebble-sdk/3.2/

I just did a clean OS X install of Yosemite 10.10.5 with App Store Xcode 7.

**Comment by Pstoppani** [comment]
Thanks for the link @geoffballinger .  Worked like a charm :+1:

**Comment by cjwilliams** [comment]
Fix has been deployed (updated gevent to 1.1b5). Please report if you still see this install issue with the latest version of the formula.

**Comment by matthewberryman** [comment]
All working now for me.
