### ISSUE TITLE
libev in gevent 1.0.2 cannot build on OS X 10.11

### ISSUE THREAD

**Issue by medicalwei** [pebble/homebrew-pebble-sdk#19]
I am sorry to live on the bleeding edge, but libev in gevent 1.0.2 cannot build on OS X 10.11

It can be installed by upgrading the dependency to gevent 1.1a2, but I didn't test it thoroughly.

**Comment by Katharine** [comment]
We're probably going to hold off on this until it's out of alpha.

**Comment by cjwilliams** [comment]
Duplicate of #18
