### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by youtux** [pebble/homebrew-pebble-sdk#2]
I would like to help improving the `pebble-sdk` formula. So far I have seen the following problems:
* The main formula `pebble-sdk.rb` lacks of some requirements listed on the [Mac OS Install Guide](http://developer.getpebble.com/sdk/install/mac/), in particular: `boost-python`, `glib` and `pixman`.
* The dependency `pebble-toolchain` of the `pebble-sdk.rb` formula is declared as build-time dependency, while it should be a normal dependency since it is required at runtime, too.
* The `depends_on :macos => :mountain_lion` dependency was required when the toolchain was compiled from sources. The Homebrew Test Bot could not compile it under Lion, so we added that dependency (see https://github.com/Homebrew/homebrew/pull/27740). Now that you use the pre-compiled toolchain (which I think it works with Lion, too) this dependency is no longer required, unless something else breaks on OSX < ML.
* Homebrew currently prefers `sha256` checksums over `sha1`, but that's not a big deal.

I want to remark that these are not complaints, but just some suggestion I would like to give you.
If you find them useful, you may also want to check the `pebble-sdk` I'm currently maintaining at [youtux/homebrew-youtux](https://github.com/youtux/homebrew-youtux).

**Comment by cjwilliams** [comment]
Thanks! We'll be updating the brew recipe again shortly, but we wanted to make it available so the kind folks at homebrew could close out their issue.

**Comment by youtux** [comment]
Yeah, the formula was stuck on 2.8.1 unfortunately so I decided to keep my own tap to allow me and my friends to update automatically when a new DP comes out.

**Comment by cjwilliams** [comment]
We're also missing attributions in the README right now, but that will also be published soon. =(

**Comment by cjwilliams** [comment]
Thank you for the suggestions (and pointing out some of the mistakes!). Everything has been addressed except for the `sha256` checksums. I'll leave this issue open until those land.

**Comment by cjwilliams** [comment]
`sha256` issue resolved with dc82ad8e2758126943f827eab906ec9d395f3447, closing this issue.
