### ISSUE TITLE
3.2 SDK 'couldn't understand kern.osversion' error

### ISSUE THREAD

**Issue by exiva** [pebble/homebrew-pebble-sdk#20]
Getting this error while installing the 3.2 SDK.

    ==> Downloading https://pypi.python.org/packages/source/p/pyasn1-modules/pyasn1-modules-0.0.5.tar.gz
    ######################################################################## 100.0%
    ==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1317, in get_metadata
         return self._get(self._fn(self.egg_info,name))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1381, in _get
        return self.loader.get_data(path)
    zipimport.ZipImportError: bad local file header in /usr/local/Cellar/pebble-sdk/3.2/libexec/lib/python2.7/site-packages/pyasn1_modules-0.0.5-py2.7.egg
    couldn't understand kern.osversion `14.4.0'

**Comment by myktra** [comment]
+1!

```
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1317, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1381, in _get
    return self.loader.get_data(path)
zipimport.ZipImportError: bad local file header in /usr/local/Cellar/pebble-sdk/3.2/libexec/lib/python2.7/site-packages/pyasn1_modules-0.0.5-py2.7.egg
```

**Comment by cjwilliams** [comment]
What version of gcc are you running @myktra and @exiva?

**Comment by exiva** [comment]
travis at Travis-MacBook-Pro in ~
	$ gcc -v
	Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
	Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
	Target: x86_64-apple-darwin14.4.0
	Thread model: posix

	travis at Travis-MacBook-Pro in ~
	$ uname -a
	Darwin Travis-MacBook-Pro.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

**Comment by ktaragorn** [comment]
Im having this issue too

**Comment by myktra** [comment]
I'm aware I'm running Xcode 6.3.1 rather than 6.4, and had planned to update - but perhaps wasn't expecting 6.4 to be a requirement per se for brewing the Pebble SDK.

```
$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: f22a0422131297304aabfc634a5fb803d3282235
Last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
OS X: 10.10.3-x86_64
Xcode: 6.3.1
CLT: 6.3.0.0.1.1428348375
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.2.2/bin/ruby
Java: N/A
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

Warning: Your Xcode (6.3.1) is outdated
Please update to Xcode 6.4.
Xcode can be updated from the App Store.
```

**Comment by cjwilliams** [comment]
For what it's worth, I'm running 6.3 and having no issues, but it's helpful information to have for debugging. Thanks!

**Comment by ManuDevelopia** [comment]
+1

==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1317, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1381, in _get
    return self.loader.get_data(path)
zipimport.ZipImportError: bad local file header in /usr/local/Cellar/pebble-sdk/3.2/libexec/lib/python2.7/site-packages/pyasn1_modules-0.0.5-py2.7.egg

**Comment by compwron** [comment]
+1 

````
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1317, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1381, in _get
    return self.loader.get_data(path)
zipimport.ZipImportError: bad local file header in /usr/local/Cellar/pebble-sdk/3.2/libexec/lib/python2.7/site-packages/pyasn1_modules-0.0.5-py2.7.egg
couldn't understand kern.osversion `14.3.0'

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/pebble/homebrew-pebble-sdk/issues



brew doctor
...
    /usr/local/include/node/uv-darwin.h
    /usr/local/include/node/uv-errno.h
    /usr/local/include/node/uv-linux.h
    /usr/local/include/node/uv-sunos.h
    /usr/local/include/node/uv-threadpool.h
    /usr/local/include/node/uv-unix.h
    /usr/local/include/node/uv-version.h
    /usr/local/include/node/uv-win.h
    /usr/local/include/node/uv.h
    /usr/local/include/node/v8-debug.h
    /usr/local/include/node/v8-platform.h
    /usr/local/include/node/v8-profiler.h
    /usr/local/include/node/v8-testing.h
    /usr/local/include/node/v8-util.h
    /usr/local/include/node/v8.h
    /usr/local/include/node/v8config.h
    /usr/local/include/node/v8stdint.h
    /usr/local/include/node/zconf.h
    /usr/local/include/node/zlib.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    phantomjs

Warning: Your Xcode (6.2) is outdated
Please update to Xcode 6.4.
Xcode can be updated from the App Store.

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:

    libxml2
    openssl
GM20437:~/bc/geekon/pebble$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: eac4b0a603a840a59fdbbb3ac5977f4bf5375afa
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: 6.2
CLT: 6.3.0.0.1.1428348375
couldn't understand kern.osversion `14.3.0'
GCC-4.2: build 5666
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/me/.rvm/rubies/ruby-2.1.5/bin/ruby
Java: 1.8.0_40
GM20437:~/bc/geekon/pebble$
````

I am upgrading Xcode but it is taking a while. I will try to come back with the results of that.

**Comment by myktra** [comment]
Potential workaround for those who just want to get running with the SDK:

```
brew install -vd pebble-sdk
```

When it has trouble with pyasn, enter Ruby and then exit to allow brewing to continue:

```
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 4
When you exit this IRB session, execution will continue.
irb(pebble-sdk):001:0> exit
```

Seems like the 3.2 SDK is installed, presumably without the services of pyasn, however that may impact things. I was able to install a basic app to the Pebble emulator (basalt) without any trouble, but I haven't done any exhaustive testing with the pebble tool. HTH.

**Comment by compwron** [comment]
@myktra 's fix worked for me. 

````
==> Summary
🍺  /usr/local/Cellar/pebble-sdk/3.2: 1713 files, 130M, built in 8.6 minutes
````

**Comment by johanhammar** [comment]
There is a newer version of pyasn1-modules (pyasn1-modules 0.0.6) which seems to be installed correctly. However I haven't tested it so I don't know if it works with the pebble tool.

**Comment by cjwilliams** [comment]
Bumping the version of oauth2client and pyasn1 and pyasn1-modules resolves the issue. However, there appears to be another issue triggered by having pyasn1 and pyasn1-modules installed after oauth2client. Continuing to investigate.

**Comment by cjwilliams** [comment]
Please test and confirm this is working for you as well. An earlier version of this fix resolved the install issue for some developers, but the ordering of the install was still causing issue for others. Please let me know if you are still seeing the error above.

**Comment by exiva** [comment]
Confirmed, works.

**Comment by myktra** [comment]
Yep, all good, thanks!

**Comment by GilDev** [comment]
Working, thanks a lot!
