### ISSUE TITLE
OS X 10.11 (El capitan beta) compatibility

### ISSUE THREAD

**Issue by jorjun** [pebble/homebrew-pebble-sdk#25]
==> python setup.py install --prefix=/usr/local/Cellar/pebble-sdk/3.2/libexec
libev/ev.c:832:26: note: expanded from macro 'ecb_noreturn'
  #define ecb_noreturn   _Noreturn
                         ^
1 error generated.
error: command 'clang' failed with exit status 1

**Comment by cjwilliams** [comment]
Possibly a duplicate of #18?

**Comment by youtux** [comment]
This seems to be related to gevent. I solved it using the master branch of gevent with the cython dependency.

**Comment by Katharine** [comment]
Duplicates #19 and #18.
