### ISSUE TITLE
Solved! - Error updating SDK

### ISSUE THREAD

**Issue by Asrycada** [pebble/homebrew-pebble-sdk#28]
So, when i tried to update my SDK, everything was perfect until the last component. Here is a screenshoot of the error. For some reason i cant run compiled C programs.

![troubleshooting](https://cloud.githubusercontent.com/assets/9388081/10056309/da6fc080-623a-11e5-980d-4702e816016e.png)

**Comment by Asrycada** [comment]
Ok, i just type:

> xcode-select --install

And it solves the last error, but now it appears this one:

![noreturn](https://cloud.githubusercontent.com/assets/9388081/10057006/5d9036fe-623e-11e5-942c-fe1cf5315cc7.png)

**Comment by HeikoKanzler** [comment]
Same issue here.

**Comment by Asrycada** [comment]
I readed yesterday on internet that the problem comes by the OS. MAC has not provide an gcc by default. I tried to install it manually but the same error comes again. So i dont know what i must to do. I'm blocked. Let's see if someone help us @HeikoKanzler

**Comment by HeikoKanzler** [comment]
@Asrycada Look at the other thread here, it's already solved :)

This works:
brew upgrade https://gist.githubusercontent.com/geoffballinger/9cc7fa234aa8873fdca1/raw/ba7175eb02b3dd9fd858b9d51599146affe97344/pebble-sdk.rb

**Comment by Asrycada** [comment]
## SOLVED! <h2> 

Its all explained in this  post: https://github.com/pebble/homebrew-pebble-sdk/issues/18

By the way, if you have same error than me, just copypaste this and click enter

> brew install https://gist.githubusercontent.com/Katharine/02bd07d4e934413504b5/raw/ddf9b060a916620adc380d769ab787699c422b33/pebble-sdk.rb

And done :+1:  :)
