### ISSUE TITLE
Error: Cannot link pebble-sdk

### ISSUE THREAD

**Issue by BorzdeG** [pebble/homebrew-pebble-sdk#50]
`brew install pebble/pebble-sdk/pebble-sdk`

output:
```
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/pebble-sdk/4.5/libexec --single-version-externally-managed --record=installed.txt
Error: undefined method `undent' for #<String:0x00000001033cf290>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/pebble/homebrew-pebble-sdk/pebble-sdk.rb:228:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:17:in `caveats'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `empty?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:610:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:659:in `finish'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>
```

https://gist.github.com/BorzdeG/90adbf720c305f7b42c53cee24bf6e08

**Comment by jpcastberg** [comment]
I was able to resolve this issue by running the following commands:

- uninstall pebble-sdk
`brew uninstall pebble-sdk`

- cd into the homebrew-pebble-sdk directory
`cd /usr/local/Homebrew/Library/Taps/pebble/homebrew-pebble-sdk/`

- remove the remote origin of the homebrew-pebble-sdk repository
`git remote rm origin`

- add a new remote 'origin' that references the pebble-dev fork of this repo
`git remote add origin https://github.com/pebble-dev/homebrew-pebble-sdk.git`

- update the repo with the new commits from the pebble-dev fork
`git pull origin master`

- install pebble-sdk
`brew install pebble-sdk`

After that, I initialized the [rocky.js watchface tutorial](https://developer.rebble.io/developer.pebble.com/tutorials/js-watchface-tutorial/part1/index.html) in a separate directory, and followed the instructions. Everything seems to be working now!
